images=["images/cat1.png", "images/dog1.jpeg","images/puppy1.jpeg","images/unicorn.png"]
captions=["Cute cat - AI generated", "Cute dog - AI Generated", "Cute Puppy - AI Generated", "Cute unicorn - AI Generated"]